# Generated by Django 4.0.3 on 2023-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0),
        ),
    ]
