# Generated by Django 4.0.3 on 2023-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0004_rename_title_post_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='post_created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='difficulty',
            new_name='post_difficulty',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='post_updated_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='', null=True, upload_to='chicks/', verbose_name='Model_pic'),
        ),
    ]
