# Generated by Django 4.0.3 on 2023-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0005_alter_post_options_rename_content_post_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='', null=True, upload_to='chicks/'),
        ),
    ]
