# Generated by Django 4.0.3 on 2023-04-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0009_rename_slug_post_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_slug',
            new_name='slug',
        ),
    ]
