# Generated by Django 4.0.3 on 2023-04-03 19:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0010_rename_post_slug_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200, unique=True, verbose_name='blog_title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='blog_slug')),
                ('blog_pic', models.ImageField(default='', null=True, upload_to='chicks/', verbose_name='blog_pic')),
                ('blog_updated_on', models.DateTimeField(auto_now=True, verbose_name='blog_updated_on')),
                ('blog_content', ckeditor.fields.RichTextField(verbose_name='blog_content')),
                ('blog_created_on', models.DateTimeField(auto_now_add=True, verbose_name='blog_created_on')),
            ],
            options={
                'ordering': ['-blog_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, unique=True, verbose_name='project_title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='project_slug')),
                ('project_pic', models.ImageField(default='', null=True, upload_to='chicks/', verbose_name='project_pic')),
                ('project_updated_on', models.DateTimeField(auto_now=True, verbose_name='project_updated_on')),
                ('project_content', ckeditor.fields.RichTextField(verbose_name='project_content')),
                ('project_created_on', models.DateTimeField(auto_now_add=True, verbose_name='project_created_on')),
                ('project_difficulty', models.IntegerField(choices=[(0, 'Coding'), (1, 'Mini-Project'), (2, 'Project')], default=0, verbose_name='project_proj')),
            ],
            options={
                'ordering': ['-project_created_on'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(verbose_name='post_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='post_created_on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, verbose_name='post_difficulty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='False', null=True, upload_to='chicks/', verbose_name='post_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='post_title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='post_updated_on'),
        ),
    ]
