# Generated by Django 4.0.3 on 2023-04-03 19:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importpython', '0011_blog_project_alter_post_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_difficulty',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_summary',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='blog_summary'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_summary',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='post_summary'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_summary',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='project_summary'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(choices=[(0, 'Coding'), (1, 'Mini-Project'), (2, 'Project')], default=0, null=True, verbose_name='project_type'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='blog_content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='blog_created_on'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(default='False', null=True, upload_to='chicks/', verbose_name='blog_pic'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='blog_title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='blog_updated_on'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='blog_slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='post_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='post_created_on'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0, null=True, verbose_name='post_difficulty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='post_title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='post_slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='project_content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='project_created_on'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='False', null=True, upload_to='chicks/', verbose_name='project_pic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='project_title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='project_updated_on'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='project_slug'),
        ),
    ]
